### ISSUE TITLE
BooleanOption.parseValue ignores arguments and always set to true

### ISSUE THREAD

**Issue by PeterVermont** [purcell/jargs#12]
This seems odd to me. I would expect that if user passes --myBooleanOption false that it should parse this.

Perhaps if they just has --myBooleanOption all by itself I would consider it true.

Not sure what the gnu rules are.

**Comment by purcell** [comment]
Hi Peter. Jargs just follows the GNU example here: there's no way to pass a value to `--myBooleanOption`. It's either present (`true`) or absent (`false`). It would probably be possible to write a different, custom, type of `Option` which accepted an explicit `true`/`false` value.

**Comment by PeterVermont** [comment]
I understand. It also appears that since wantsValue is set to false by the constructor that the parseValue method will never get called. My mistake.
