### ISSUE TITLE
Intention of remove in getOptionValue

### ISSUE THREAD

**Issue by JackLeEmmerdeur** [purcell/jargs#13]
Although the activities around this project seem to have stopped, I am still using it and I have an issue with the code.

 It would be a relief for me to know what you intended with line 472 of the in CmdLineParser.java, Steve. Why are you removing the entries from the values-Hashmap. It prevents to use getOptionValue more than once. Do I have to use parse again, if I want to query for the same option multiple times?

For now I have replaced .remove() with .get() in my local version of the project, but that results in an infinite while-loop in the unit-test testMultipleUses() in CmdLineParserTestCase.java. because the condition b == null is never true, which tells me you're doing the remove on purpose. 

Is it safe for me to use .get() and @ignore the unit-test? Thx.

**Comment by ooxi** [comment]
If you have specified the same argument multiple times, you will only get the first value if you replace [`.remove(0)`](https://github.com/purcell/jargs/blob/master/src/main/java/com/sanityinc/jargs/CmdLineParser.java#L472) with `.get(0)`

**Comment by JackLeEmmerdeur** [comment]
That was impressively  fast and you're not even a member of the project. So thanks for clarification. If you're using the lib in one of your projects, you never had a problem with that row? When would a user pass the same option 2x, no matter if long- and short-form mixed or 2 times short-form? This could only happen accidentially, right? And if so, which one of the double-options should I as an implementer regard?

I would use the one passed at the back of the command-line or implement getOptionValue using an Iterator. For now I think, I'll rewrite my code to use a LinkedHashMap (ordering) and if there's a double-option, I'll use the last passed.

BTW: You got some nice. Definitley will take a look in the traffic-light sim, as I want to learn more about node. If I'm right (deducting from the readme of wms) we could talk in our mother-tounge. Tsch(ö) mit ö.

**Comment by JackLeEmmerdeur** [comment]
Sorry I got it wrong. No need for a LinkedHashMap. The values each value-HashMap entry are put as an ArrayList, so they are ordered in the way passed to the command line. But the concept of my idea hasn't changed and I implement it, to overcome this trivial bugger.

**Comment by JackLeEmmerdeur** [comment]
Doh! If I only had a closer look on the test-case testMultipleUses(). Now multiple usage of the same option isn't that useless anymore with the verbosity switch. I'll nevertheless will update my fork of the repo with my code changes.

**Comment by purcell** [comment]
Hi, I guess now that you've found the test case this issue can be closed? I'll go ahead and do that, but feel free to reopen if you think this is a genuine bug and is inconsistent with the behaviour of GNU `getopt`. :-)

**Comment by ooxi** [comment]
@JackLeEmmerdeur thank you for the flowers :) I used jargs excessivly in the past, nowerdays I prefer [args4j](http://args4j.kohsuke.org/). In my opinion jargs is mightier but most of the time I only need a couple of command line switches without advanced logic.
