### ISSUE TITLE
iterating over options and values

### ISSUE THREAD

**Issue by ag88** [purcell/jargs#14]
hi thanks for creating this cool jargs processing class

i'd like to suggest adding iterator access so that it would be possible to iterate over the options and values

e.g. on the apps side:
```
Iterator<Option<?>> options_iter = parser.iterator();
while(options_iter.hasnext()) {
    Option opt = iter.next();
    switch(opt.longForm()) {
    case "option1":
        values = parser.getOptionValues(opt)
        ...
        break;
    case "option2":
       ....
       break;
```
just a 2 cents suggestion :)

**Comment by ooxi** [comment]
If you want to switch over the option long name, you already have to know all options. Therefore an access to `parser.getOptionValue` would be much easier and also typesafe.

**Comment by purcell** [comment]
Thanks @ag88 for taking the time to make the suggestion, but I agree with @ooxi in this case and will close this issue, sorry.
